# Generated by Django 5.2.1 on 2025-05-20 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_budget_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='num_sections',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
