# Generated by Django 5.2.1 on 2025-05-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_budget_num_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='num_sections',
        ),
        migrations.AddField(
            model_name='budget',
            name='allocations',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Allocation',
        ),
    ]
