# Generated by Django 5.2.1 on 2025-05-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_budget_num_sections_budget_allocations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
