# Generated by Django 5.2.1 on 2025-05-27 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transaction_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 27)),
        ),
    ]
