# Generated by Django 5.2.1 on 2025-05-27 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_budget_monthly_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 27, 19, 24, 9, 797355, tzinfo=datetime.timezone.utc)),
        ),
    ]
